/*
 * timer_config.h
 *
 *  Created on: Feb 9, 2023
 *      Author: lenovo
 */

#ifndef TIMER_TIMER_CONFIG_H_
#define TIMER_TIMER_CONFIG_H_
#define TIMER0_OVF_INT_ID 0
#define TIMER0_CMP_INT_ID 1
#define FCPU 16
/*PLEASE CHOOSE FROM :
 * TIMER0_NORMAL_MODE
 * TIMER0_CTC_MODE
 * TIMER0_FAST_PWM_MODE
 * TIMER0_PHASECORRECT_MODE
 * */
#define TIMER0_MODE			TIMER0_PHASECORRECT_MODE


/*PLEASE CHOOSE PRESCALER :
 * TIMER0_PRESCALER_NO_CLOCK
 * TIMER0_PRESCALER_NO_PRESCALER
 * TIMER0_PRESCALER_8
 * TIMER0_PRESCALER_64
 * TIMER0_PRESCALER_256
 * TIMER0_PRESCALER_1024
 * TIMER0_PRESCALER_EXTCLK_FALL_EDGE
 * TIMER0_PRESCALER_EXTCLK_RAISING_EDGE
 * */
#define TIMER0_PRESCALER	TIMER0_PRESCALER_1024

/*PLEASE CHOOSE OC0 PIN MODE
 * FOR NON PWM
 * TIMER0_OC0_MODE_DISSCONECTED
 * TIMER0_OC0_MODE_TOGGLE
 * TIMER0_OC0_MODE_CLEAR
 * TIMER0_OC0_MODE_SET
 *
 * for PWM :
 * TIMER0_PWM_NON_INVERTED
 * TIMER0_PWM_INVERTED
 * */
#define TIMER0_OC0_MODE		TIMER0_PWM_NON_INVERTED


#endif /* TIMER_TIMER_CONFIG_H_ */
